name = "nobishiro-shindan"
compatibility_date = "2026-07-25"
main = "src/index.js"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "nobishiro-shindan-db"
database_id = "57f0e037-1ee0-4256-b019-acbda31f6e66"
